USE [master]
GO
/****** Object:  Database [SistemDataSiswa_SAS]    Script Date: 01/12/2025 01:01:30 ******/
CREATE DATABASE [SistemDataSiswa_SAS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SistemDataSiswa_SAS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\SistemDataSiswa_SAS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SistemDataSiswa_SAS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\SistemDataSiswa_SAS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SistemDataSiswa_SAS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET ARITHABORT OFF 
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET  MULTI_USER 
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET QUERY_STORE = ON
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [SistemDataSiswa_SAS]
GO
/****** Object:  Table [dbo].[Tabel Siswa]    Script Date: 01/12/2025 01:01:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tabel Siswa](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nisn] [varchar](20) NULL,
	[nama] [nchar](10) NULL,
	[kelas] [varchar](20) NULL,
	[jurusan] [varchar](50) NULL,
	[nilai_akhlak] [varchar](2) NULL,
	[rata_nilai] [float] NULL,
 CONSTRAINT [PK_Tabel Siswa] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tabel User]    Script Date: 01/12/2025 01:01:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tabel User](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[username] [varchar](50) NULL,
	[password] [varchar](50) NULL,
 CONSTRAINT [PK_Tabel User] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Tabel User] ON 

INSERT [dbo].[Tabel User] ([id], [username], [password]) VALUES (1, N'Vega', N'Vega123')
INSERT [dbo].[Tabel User] ([id], [username], [password]) VALUES (2, N'siswa', N'siswa')
SET IDENTITY_INSERT [dbo].[Tabel User] OFF
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Tabel Siswa]    Script Date: 01/12/2025 01:01:31 ******/
ALTER TABLE [dbo].[Tabel Siswa] ADD  CONSTRAINT [IX_Tabel Siswa] UNIQUE NONCLUSTERED 
(
	[nisn] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [SistemDataSiswa_SAS] SET  READ_WRITE 
GO
